baseURL = "https://alxnd3r.github.io/PORTAFOLIO/"
languageCode = "es-mx"
title = "Mi Portafolio"
theme = "ananke"

# Para GitHub Pages
canonifyURLs = true
relativeURLs = false

[params]
  mainSections = []